"""Build results/final_comparison.json and results/report_tables.md from stored results (no new computation)."""
import json, numpy as np
from summarize import cv_summary, loso_summary
from pipeline import TASK_ORDER
from common import RES, write_json
T = json.load(open(RES / "final_test_results.json")); V = json.load(open(RES / "variants.json"))
CFG = {"V6b_best_model": "V6b_filter1000_STRING", "V6a_best_simple_baseline": "V6a_filter1000_LR", "C1_study_only_reference": "C1_study_only"}
NAME = {"V6b_best_model": "Best model: V6b (filter-1000 + STRING smoothing + LR)", "V6a_best_simple_baseline": "Best simple baseline: V6a (filter-1000 + LR)",
        "C1_study_only_reference": "Reference control: C1 study-only"}
comp = {"versions": T["versions"], "tasks": {}}
md = ["# Final comparison tables (generated by scripts/build_report_tables.py)\n"]
for t in TASK_ORDER:
    tt = T["tasks"][t]; ch = tt["chance_test"]
    md.append(f"\n## {t}\n\nTest n = {tt['n_test']} {tt['test_class_n']}; train n = {tt['n_train']}. "
              f"Test chance macro-F1: uniform {ch['uniform_random_macroF1']:.3f}, prior {ch['prior_random_macroF1']:.3f}, majority {ch['majority_class_macroF1']:.3f}; MCC 0; AUC 0.5.\n")
    md.append("| Configuration | (1) Locked test macro-F1 [95% CI] | test MCC [CI] | test AUC [CI] | (2) Dev 5×5 CV macro-F1 mean ± fold SD (seed SD) | CV MCC | CV AUC | (3) Leave-one-cohort-out macro-F1 (per held-out cohort) |")
    md.append("|---|---|---|---|---|---|---|---|")
    comp["tasks"][t] = {}
    for k, cfg in CFG.items():
        m = tt["models"][k]; mm = m["metrics"]; ci = m["ci95"]; cv = cv_summary(cfg, t); lo = loso_summary(cfg, t)
        comp["tasks"][t][k] = {"config": cfg, "test": {"metrics": mm, "ci95": ci, "complete_batch_subset": m["complete_batch_subset"]},
                               "cv": cv, "loso": lo, "chance_test": ch}
        los = "; ".join(f"{c} {v['macro_f1']:.3f} (n={v['n_test']}, chance {v['chance_uniform_macroF1']:.2f})" for c, v in lo.items())
        md.append(f"| {NAME[k]} | **{mm['macro_f1']:.3f}** [{ci['macro_f1'][0]:.3f}, {ci['macro_f1'][1]:.3f}] | {mm['mcc']:.3f} [{ci['mcc'][0]:.2f}, {ci['mcc'][1]:.2f}] | "
                  f"{mm['auc']:.3f} [{ci['auc'][0]:.2f}, {ci['auc'][1]:.2f}] | {cv['macro_f1_mean']:.3f} ± {cv['macro_f1_fold_sd']:.3f} ({cv['macro_f1_seed_sd']:.3f}) | "
                  f"{cv['mcc_mean']:.3f} | {cv['auc_mean']:.3f} | {los} |")
    md.append("\nPer-class precision / recall and confusion matrices (rows = true, columns = predicted, label order shown):\n")
    for k, cfg in CFG.items():
        mm = tt["models"][k]["metrics"]; cv = comp["tasks"][t][k]["cv"]
        pc = ", ".join(f"{c}: P {v['precision']:.2f} / R {v['recall']:.2f}" for c, v in mm["per_class"].items())
        pcv = ", ".join(f"{c}: P {v['precision']:.2f} / R {v['recall']:.2f}" for c, v in cv["per_class_pooled"].items())
        md.append(f"- **{NAME[k]}**. Test: {pc}; CM {mm['confusion_matrix']['labels']} = {mm['confusion_matrix']['matrix']}. "
                  f"CV (pooled over 25 folds): {pcv}; CM summed = {cv['confusion_matrix_summed_over_folds_and_seeds']['matrix']}.")
    g = tt["graph_effect_V6b_minus_V6a"]
    md.append(f"\nGraph effect on test (V6b − V6a, paired bootstrap): {g['macro_f1_diff']:+.3f} [{g['ci95'][0]:+.3f}, {g['ci95'][1]:+.3f}].\n")
md.append("\n## All variants (development 5×5 CV macro-F1; running budget count)\n\n| id | family | count | eligible | SCZ | BD | MDD | Task B | mean | verdict |\n|---|---|---|---|---|---|---|---|---|---|")
for r in V["variants"]:
    if r["config"] is None:
        md.append(f"| {r['id']} | {r['family']} | – | no | – | – | – | – | – | {r['verdict']} |"); continue
    md.append(f"| {r['id']} | {r['family']} | {r['running_count'] or '–'} | {'yes' if r['eligible_for_final'] else 'no'} | " +
              " | ".join(f"{r[t]:.3f}±{r[t+'_sd']:.3f}" for t in TASK_ORDER) + f" | {r['mean_4_tasks']:.3f} | {r['verdict']} |")
(RES / "report_tables.md").write_text("\n".join(md))
write_json(comp, RES / "final_comparison.json")
print("\n".join(md))
